In [1]:
import nltk

In [2]:
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to
[nltk_data]     /home/a9dbe709-a32c-486d-9702-40950e59edeb/nltk_data..
[nltk_data]     .
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/a9dbe709-a32c-486d-9702-40950e59edeb/nltk_data..
[nltk_data]     .
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/a9dbe709-a32c-486d-9702-40950e59edeb/nltk_data..
[nltk_data]     .
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /home/a9dbe709-a32c-486d-9702-40950e59edeb/nltk_data..
[nltk_data]     .
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /home/a9dbe709-a32c-486d-9702-40950e59edeb/nltk_data..
[nltk_data]     .
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [3]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk import pos_tag

In [4]:
text= "Machine learning is very interesting and useful for data analysis."

In [5]:
tokens=word_tokenize(text)
print(tokens)

['Machine', 'learning', 'is', 'very', 'interesting', 'and', 'useful', 'for', 'data', 'analysis', '.']


In [6]:
pos= pos_tag(tokens)
print(pos)

[('Machine', 'NN'), ('learning', 'NN'), ('is', 'VBZ'), ('very', 'RB'), ('interesting', 'JJ'), ('and', 'CC'), ('useful', 'JJ'), ('for', 'IN'), ('data', 'NN'), ('analysis', 'NN'), ('.', '.')]


In [7]:
stop_words= set( stopwords.words('english'))
filtered= [ w for w in tokens if w.lower() not in stop_words]
print("After stop word removal:", filtered)

After stop word removal: ['Machine', 'learning', 'interesting', 'useful', 'data', 'analysis', '.']


In [8]:
ps= PorterStemmer()
stemmed= [ps.stem(w) for w in filtered]
print("Stemmed words:", stemmed)

Stemmed words: ['machin', 'learn', 'interest', 'use', 'data', 'analysi', '.']


In [9]:
lm= WordNetLemmatizer()
lemmatized= [lm.lemmatize(w) for w in filtered]
print(lemmatized)

['Machine', 'learning', 'interesting', 'useful', 'data', 'analysis', '.']


In [10]:
from sklearn.feature_extraction.text import CountVectorizer
doc = [
  "machine learning is fun",
  "learning is powerful"
]
cv = CountVectorizer()
tf= cv.fit_transform(doc)
print(cv.get_feature_names_out())

['fun' 'is' 'learning' 'machine' 'powerful']


In [11]:
print(tf.toarray())

[[1 1 1 1 0]
 [0 1 1 0 1]]


In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf= TfidfVectorizer()
result= tfidf.fit_transform(doc)
print("words:",tfidf.get_feature_names_out())
print("TF-IDF:",result.toarray())

words: ['fun' 'is' 'learning' 'machine' 'powerful']
TF-IDF: [[0.57615236 0.40993715 0.40993715 0.57615236 0.        ]
 [0.         0.50154891 0.50154891 0.         0.70490949]]
